trigger:

- main

pool:
  vmImage: windows-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
      displayName: 'Checkout source code'

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    - script: |
        echo "Current working directory: $(System.DefaultWorkingDirectory)"
        ls -la $(System.DefaultWorkingDirectory)
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
         **\bin\**\*test.dll
         **\bin\**\*tests.dll
         searchFolder: '$(System.DefaultWorkingDirectory)'
          distributionBatchType: 'basedOnExecutionTime'
